edgexfoundry/device-sdk-c

- src/c/config.c
- src/c/config.h
- src/c/errorlist.h
- src/c/profiles.c
- src/c/profiles.h
- src/c/service.c
> F-2 more error checking at service startup

- TODO
- src/c/device.c
- src/c/device.h
- src/c/service.c
> F-4 Add mappings and transforms for Readings

- include/edgex/devsdk.h
- src/c/config.c
- src/c/devman.c
- src/c/edgex_rest.c
- src/c/edgex_rest.h
- src/c/metadata.c
- src/c/metadata.h
This PR addresses some memory issues in the device management code, includes deletion of addressables as part of device deletion, and implements the device update function.
> F 14 branch 2

- include/edgex/devsdk.h
- src/c/config.c
- src/c/devman.c
- src/c/edgex_rest.c
- src/c/edgex_rest.h
- src/c/metadata.c
- src/c/metadata.h
This brings the second part of the implementation of add/remove/update device functionality into Delhi, rather than leaving it half-done
> Device management API

- docs/deviceprofiles.md
- src/c/examples/res/ExampleProfile.yaml
- src/c/examples/template.c
> Add note on device profiles, fix wrong types in example

- src/c/profiles.c
> Fix memleak in profile upload code

- CHANGES
- src/c/callback.c
- src/c/callback.h
- src/c/device.c
- src/c/device.h
- src/c/discovery.c
- src/c/discovery.h
- src/c/rest_server.h
- src/c/service.c
> F-42 Implement device by name REST commands. Simplify URL path handling.

- docs/device-sdk.raml
> Add RAML for device rest api

- CHANGES
- src/c/config.c
- src/c/config.h
- src/c/edgex_rest.c
- src/c/metrics.c
- src/c/metrics.h
- src/c/service.c
Add support for SysMgt endpoints - issue #59
> F 59 branch

- docs/configuration.md
- src/c/config.c
- src/c/device.c
- src/c/examples/res/configuration.toml
- src/c/profiles.c
This fixes two inconsistencies between the C and GO device SDKs.
> Go consistency

- README.md
This PR is really only to test the verify job
> Add some docker build instructions

- CHANGES
- include/edgex/devsdk.h
- include/edgex/registry.h
- src/c/config.c
- src/c/config.h
- src/c/consul.c
- src/c/consul.h
- src/c/examples/template.c
- src/c/registry.c
- src/c/service.c
> F-69 Add registry abstraction and port consul implementation to it.

- CHANGES
- include/edgex/devsdk.h
- src/c/devman.c
> F-83 Add methods to obtain individual device metadata

- docs/configuration.md
- docs/device-sdk.raml
> Update documentation in line with behavior

- CHANGES
- docs/configuration.md
- include/edgex/registry.h
- src/c/config.c
- src/c/config.h
- src/c/consul.c
- src/c/consul.h
- src/c/registry.c
- src/c/service.c
> F-81 Get metadata and data service locations from the registry

- include/edgex/edgex.h
- src/c/data.c
- src/c/data.h
- src/c/edgex_rest.c
- src/c/edgex_time.c
- src/c/edgex_time.h
- src/c/metrics.c
- src/c/profiles.c
- src/c/service.c
- src/c/service.h
Log startup time and port in the same fashion as the other services
+ updates for metrics and value-descriptor generation
> F-91 Startup logging

- CHANGES
- include/edgex/devsdk.h
- src/c/cmdinfo.h
- src/c/data.c
- src/c/data.h
- src/c/device.c
- src/c/edgex_rest.c
- src/c/examples/template.c
- src/c/service.c
> F-102 update get/set handler interface

- docs/deviceprofiles.md
- docs/servicewritersguide.md
- include/edgex/devsdk.h
- include/edgex/edgex.h
- src/c/device.c
- src/c/edgex_rest.c
- src/c/examples/res/ExampleProfile.yaml
> Name change for profile elements as per go-mod-core-contracts #59

- docs/metrics.md
- src/c/metrics.c
Add a document indicating what the various metrics mean
> Small tweak to metrics output

- src/c/edgex_rest.c
> F-55 Null-pointer check in wrong place

- CHANGES
- README.md
- include/edgex/edgex_logging.h
- scripts/Dockerfile.alpine-3.7
- src/CMakeLists.txt
- src/c/CMakeLists.txt
- src/c/autoevent.c
- src/c/correlation.c
- src/c/correlation.h
- src/c/edgex_logging.c
- src/c/examples/template.c
- src/c/rest.c
- src/c/rest_server.c
- src/c/service.c
- src/cmake/FindLibUUID.cmake
+ Reformat log output in line with other EdgeX services.
Implements #86 
> F-86 Add Correlation ID tracking.

- .gitignore
- include/edgex/devsdk.h
- include/edgex/edgex_logging.h
- include/edgex/registry.h
- scripts/build.sh
- src/c/CMakeLists.txt
- src/c/autoevent.c
- src/c/config.c
- src/c/config.h
- src/c/consul.c
- src/c/consul.h
- src/c/data.c
- src/c/data.h
- src/c/discovery.c
- src/c/edgex_logging.c
- src/c/edgex_rest.c
- src/c/edgex_rest.h
- src/c/examples/template.c
- src/c/metadata.c
- src/c/metadata.h
- src/c/profiles.c
- src/c/registry.c
- src/c/rest.c
- src/c/rest.h
- src/c/rest_server.c
- src/c/rest_server.h
- src/c/service.c
- src/c/service.h
> Update to current iotech-c-utils

- CHANGES
- TODO
- include/edgex/device-mgmt.h
- include/edgex/edgex.h
- src/c/config.c
- src/c/devmap.c
- src/c/devmap.h
- src/c/edgex_rest.c
- src/c/edgex_rest.h
- src/c/profiles.c
- src/c/profiles.h
- src/c/rest.c
- src/c/service.c
> Adds device profile management API

- src/c/autoevent.c
> Fix segfault on exit when autoevent initialization has failed

- CHANGES
- docs/configuration.md
- src/c/config.c
- src/c/config.h
- src/c/device.c
- src/c/examples/counters/res/configuration.toml
- src/c/examples/random/res/configuration.toml
- src/c/examples/res/configuration.toml
As per #124  / https://github.com/edgexfoundry/device-sdk-go/issues/303
> F-124 Remove ReadMaxLimit

- CHANGES
- docs/configuration.md
- src/c/config.c
- src/c/config.h
- src/c/examples/counters/res/configuration.toml
- src/c/examples/random/res/configuration.toml
- src/c/examples/res/configuration.toml
- src/c/service.c
> F-126 Bring logger config into line with other EdgeX services

- include/edgex/eventgen.h
- src/c/examples/template.c
> Fix wrong apidoc comment

- CHANGES
- src/c/data.c
- src/c/edgex-time.c
- src/c/edgex-time.h
> F-128 use monotonic nanosecond timestamps on Events

- src/c/data.c
> Set origin timestamps on Readings if not provided by the driver

- src/c/data.c
> F-137 Set origin timestamps on Readings if not provided by the driver

- include/edgex/registry.h
- src/c/consul.c
- src/c/consul.h
- src/c/registry.c
- src/c/service.c
- src/c/service.h
> F-132 Add service deregistration from registry

- scripts/build.sh
- src/c/examples/res/configuration.toml
Revert inadvertent change to example config.
> F-140 Move iotech-c-utils dependency to a stable commit.

- src/c/edgex-time.c
> F-148 fix timestamp overflow with 32-bit time_t

- src/c/edgex-rest.c
> Manage DeviceProfile errors when parsed as part of a Device

- CHANGES
- include/edgex/device-mgmt.h
- src/c/autoevent.c
- src/c/callback.c
- src/c/devmap.c
- src/c/devmap.h
- src/c/service.h
> Add callbacks for device add/create/remove

- src/c/config.c
> Skip blank Driver configuration fields

- src/c/rest.c
…(fixes broken binary PUT on 32-bit)
> Noissue: use correct types for setting curl options 

- CHANGES
- docs/device-sdk.raml
- src/c/service.c
> Add /api/version endpoint (issue #166)

- scripts/build.sh
- src/c/edgex-logging.c
- src/c/edgex-rest.c
+ Compatibility fixes for 32-bit
> Quote msg part of log messages (#168)

- src/c/metadata.c
- src/c/metadata.h
- src/c/profiles.c
> Only create ValueDescriptors if core-metadata won't (#139)

- src/c/data.c
> fix cbor memleak

- docs/configuration.md
- docs/device-sdk.raml
- src/c/examples/README.md
- src/c/examples/counters/README.md
- src/c/examples/counters/res/configuration.toml
- src/c/examples/random/README.md
- src/c/examples/random/res/configuration.toml
- src/c/examples/res/configuration.toml
> Update examples and documentation to consistently use port 49999 (#161)

- src/c/service.c
> Update device service addressable if necessary (#177)

- src/c/service.c
> Avoid segfault in service_free where service_start hasn't been called

- src/c/CMakeLists.txt
- src/c/config.c
- src/c/examples/counters/device-counter.c
- src/c/examples/random/device-random.c
- src/c/examples/random/res/RandomExampleProfile.yaml
- src/c/examples/res/TemplateProfile.yaml
- src/c/examples/template.c
- src/c/service.c
Addresses #182 
Also fix loglevel setting at startup, use the atomics library if needed (eg, Raspbian) and simplify the example code for waiting for interrupt
> Remove redundant parts of example device profiles

- src/c/cmdinfo.h
- src/c/device.c
- src/c/edgex-rest.c
(default is ResourceOperation/Parameter or PropertyValue/DefaultValue)
Implements #183
> Implement default values for parameters to set/PUT operations

- CHANGES
- src/c/examples/CMakeLists.txt
- src/c/examples/README.md
- src/c/examples/gyro/CMakeLists.txt
- src/c/examples/gyro/README.md
- src/c/examples/gyro/device-gyro.c
- src/c/examples/gyro/res/Gyro.yaml
- src/c/examples/gyro/res/configuration.toml
- src/c/examples/terminal/CMakeLists.txt
- src/c/examples/terminal/README.md
- src/c/examples/terminal/device-terminal.c
- src/c/examples/terminal/res/Terminal.yaml
- src/c/examples/terminal/res/configuration.toml
> Add examples of deviceResource aggregation (#181)

- CHANGES
- Makefile
- docs/deviceprofiles.md
- include/edgex/edgex.h
- scripts/Dockerfile.alpine-3.7
- src/c/device.c
- src/c/edgex-rest.c
- src/c/examples/gyro/res/Gyro.yaml
- src/c/examples/terminal/res/Terminal.yaml
Use "deviceResource" in preference to "object"
Marshal new "deviceCommand" field although it is NYI
Addresses #129 
+ update the Dockerfile for the "terminal" example and add a toplevel Makefile
> Use new ResourceOperation fields

- Attribution.txt
- README.md
> Add detail on required software, update attributions (#197)

- src/c/config.c
- src/c/config.h
- src/c/service.c
> Allow registry location to be found in config toml (#195)

- src/c/config.c
> Allow for floats in TOML configuration

- src/c/callback.c
> Change test for service being started as logger gets set up earlier

- Jenkinsfile
- Makefile
- scripts/Dockerfile.alpine-3.9
- scripts/Dockerfile.alpine-3.9-base
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Add Jenkinsfile to fuji branch for Geneva transformation

- include/devsdk/devsdk-base.h
- include/edgex/rest-server.h
- src/c/rest-server.c
- src/c/rest-server.h
- src/c/service.c
> Add a function allowing the implementation to have custom http endpoints (#234)

- src/c/config.c
- src/c/metadata.c
> Fix adminstate/opstate handling

- CHANGES
- src/c/data.c
> Add type information to Readings when sending to core-data (#241)

- CHANGES
- include/edgex/devices.h
- src/c/autoevent.c
- src/c/callback.c
- src/c/config.c
- src/c/config.h
- src/c/device.c
- src/c/devman.c
- src/c/devmap.c
- src/c/devmap.h
- src/c/metadata.c
- src/c/metadata.h
- src/c/service.c
Implement #215 #217 #246 
Also allow uppercase environment vars for overrides (https://github.com/edgexfoundry/go-mod-bootstrap/issues/69)
> Remaining geneva issues

- src/c/service.c
- src/c/service.h
Signed-off-by: davidr@beechwoods.com <davidr@beechwoods.com>
> Initial checkin of issue 223 (config overwrite option)

- docs/configuration.md
- docs/servicewritersguide.md
- src/c/examples/v2/counters/device-counter.c
- src/c/examples/v2/random/device-random.c
- src/c/service.c
Also update Random and Counter examples to use exceptions in the access handlers
> docs: Update for v2 API

- CHANGES
- docs/startup.md
- src/c/service.c
- src/c/service.h
- src/c/v1compat.c
See https://github.com/edgexfoundry/device-sdk-go/issues/526
> compat: Add --instance flag as per Go SDK

- src/c/v1compat.c
> compat: Add missing v1 post_readings function

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: James Gregg <james.r.gregg@intel.com>
- Add standard PR template
> Add standard PR template

- docs/startup.md
- include/edgex/rest-server.h
- src/c/callback.c
- src/c/callback.h
- src/c/config.c
- src/c/config.h
- src/c/device.c
- src/c/device.h
- src/c/discovery.c
- src/c/discovery.h
- src/c/edgex-rest.c
- src/c/edgex-rest.h
- src/c/edgex2.h
- src/c/metrics.c
- src/c/metrics.h
- src/c/rest-server.c
- src/c/rest-server.h
- src/c/service.c
Issue Number: #257 
Refactor of the toplevel http server code allows some simplification of the individual handlers.
The v2 ping endpoint is implemented and demonstrates how we might pattern the rest of the v2 endpoints handlers.
> REST v2 API 1/?

- include/devsdk/devsdk-base.h
- src/c/api.h
- src/c/config.c
- src/c/config.h
- src/c/data.c
- src/c/data.h
- src/c/device.c
- src/c/device.h
- src/c/devsdk-base.c
- src/c/edgex-rest.c
- src/c/edgex-rest.h
- src/c/edgex2.h
- src/c/rest-server.c
- src/c/service.c
- src/c/v1compat.c
Issue Number: #257 
New `config` and `device` endpoints are implemented
Note that BaseResponse use is inconsistent, this will be addressed once the content of BaseRequest / BaseResponse has been reconsidered and finalized.
> REST v2 API 2/?

- CHANGES
- docs/configuration.md
- include/edgex/devsdk.h
- include/edgex/eventgen.h
- include/edgex/registry.h
- src/c/autoevent.c
- src/c/config.c
- src/c/config.h
- src/c/edgex-logging.c
- src/c/edgex-logging.h
- src/c/edgex-rest.h
- src/c/examples/counters/res/configuration.toml
- src/c/examples/discovery/res/configuration.toml
- src/c/examples/gyro/res/configuration.toml
- src/c/examples/random/res/configuration.toml
- src/c/examples/res/configuration.toml
- src/c/examples/terminal/README.md
- src/c/examples/terminal/res/configuration.toml
- src/c/service.c
- src/c/service.h
> Remove logging service support (#274)

- CHANGES
- docs/configuration.md
- src/c/config.c
- src/c/config.h
- src/c/edgex-logging.c
- src/c/edgex-logging.h
- src/c/service.c
Logging is always to stdout
Issue Number: #281 
Re-introduced EnableRemote and File options for the logging system
> revert: Reinstate remote logging capability (#281)

- CHANGES
- include/edgex/rest-server.h
- src/c/device.c
- src/c/reqdata.c
- src/c/reqdata.h
- src/c/rest-server.c
Issue Number: #287 #289 
Boolean validation added
CBOR accepted for PUT to api/v2/device (Not implemented for v1)
> feat: process CBOR payloads in device PUT (#289)

- CHANGES
- docs/deviceprofiles.md
- include/edgex/edgex.h
- src/c/device.c
- src/c/edgex-rest.c
- src/c/profiles.c
- src/c/transform.c
- src/c/transform.h
minimum and maximum valueproperty fields are ignored
Issue Number: #211 
Request to write out-of-range data are rejected
> feat: implement minimum/maximum limits for write ops (#211)

- src/c/devman.c
- src/c/edgex-rest.c
- src/c/edgex-rest.h
- src/c/metadata.c
- src/c/metadata.h
If a device is discovered and it already exists in metadata for another device service, the discovery fails
Discovered devices which already exist are re-assigned to the discovering device service
> feat(discovery): claim extant discovered devices

- src/c/api.h
- src/c/autoevent.c
- src/c/autoevent.h
- src/c/callback2.c
- src/c/callback2.h
- src/c/config.c
- src/c/data.c
- src/c/data.h
- src/c/device.c
- src/c/devmap.c
- src/c/devmap.h
- src/c/discovery.c
- src/c/discovery.h
- src/c/edgex-rest.c
- src/c/edgex-rest.h
- src/c/metrics.c
- src/c/rest-server.c
- src/c/rest-server.h
- src/c/service.c
Issue Number: #257 
Added v2 discovery and callback endpoints.
Completed v2 device endpoint implementation by updating event/reading objects to current spec.
This PR closes #257
> feat: REST v2 Device Service endpoints (#257)

- .github/Contributing.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/semantic.yml
Commit messages are unchecked
Commit messages & PR titles are checked for type indicators
Added Contributing.md information
Updated PR template
> ci: add semantic.yml for commit linting

- src/c/consul.c
Uses `/1.0/` path as per Hanoi and earlier releases
Now uses `/2.0/` path for Ireland release
Consul configuration now in the 2.0 path
> refactor: Switch to 2.0 Consul path

- docs/configuration.md
- src/c/config.c
- src/c/examples/bitfields/res/configuration.toml
- src/c/examples/counters/res/configuration.toml
- src/c/examples/discovery/res/configuration.toml
- src/c/examples/file/res/configuration.toml
- src/c/examples/gyro/res/configuration.toml
- src/c/examples/random/res/configuration.toml
- src/c/examples/res/configuration.toml
- src/c/examples/terminal/res/configuration.toml
Configuration for supporting services uses legacy names
"Data" renamed to "edgex-core-data", "Metadata" renamed to "edgex-core-metadata"
Static configuration needs to be updated as per the examples
> fix: update Service Keys to new style (#333)

- src/c/edgex-rest.c
Core now permits attributes in device profiles to be non-string values, eg booleans, integers. If such profiles are loaded to the SDK it will crash during parse
Numerics and booleans are mapped to appropriate iot_data_t types. Structured attributes are passed as JSON strings.
> fix: allow for non-string attributes

- src/c/data-redstr.c
- src/c/data-redstr.h
- src/c/service.c
Async event push to redis fails with segfault
redis client structure populated correctly to perform async push
> fix: set up for async event push via redis

- src/c/examples/discovery/res/configuration.toml
- src/c/examples/discovery/res/devices/readme.txt
- src/c/examples/random/res/configuration.toml
- src/c/examples/random/res/profiles/RandomExampleProfile.json
Update discovery sample app configuration.toml to include devices resource directory as well which will assist in creation of discovery device/s
> fix: Update random device profile, configuration and discovery device configuration file

- CHANGES
- README.md
- scripts/Dockerfile.alpine
- scripts/Dockerfile.alpine-base
- scripts/entrypoint.sh
> build(deps): bump Alpine to 3.15

- CHANGES
- src/c/config.c
- src/c/secrets-impl.h
- src/c/secrets-insecure.c
- src/c/secrets-vault.c
- src/c/secrets.c
- src/c/secrets.h
> feat: upload secrets from file (#403)

- CHANGES
- include/edgex/rest-server.h
- src/c/config.c
- src/c/rest-server.c
- src/c/rest-server.h
- src/c/service.c
> feat: add CORS support (#389)

- src/c/consul.c
- src/c/data.c
- src/c/devmap.c
- src/c/rest-server.c
> fix: Issues #413 #417 #424

- src/c/rest-server.c
No doc update required
Run an example device service with a configuration which will cause an htttp server error, eg setting for port 80 - the log should show the specific error from microhttpd
> fix: capture and log errors from libmicrohttpd

- README.IOT.md
- README.md
> docs: Add installation instructions for IOT utilities

- src/c/metadata.c
> fix: Remove space character from the URL for uploading deviceprofile

- src/c/autoevent.c
fix: #494 
The refcount in the edgex_autoimpl structure is a legacy of the earlier scheduler implementation.
Run in debug mode and set a breakpoint at the first line of the `ae_runner` function. When the breakpoint is hit, delete the device and resume the program.
With this fix the device service is running smoothly without getting a segmentation fault.
```
level=INFO ts=2023-12-21T15:09:53Z app=device-random correlation-id=14a42ea6-c394-41c3-8bcd-a29b9f5e6835 msg="callback: Delete device RandomDevice1"
level=ERROR ts=2023-12-21T15:09:53Z app=device-random msg="Autoevent fired for unknown device RandomDevice1"
```
> fix: Remove the refcount from the autoevent impl structure

- docs/servicewritersguide.md
- include/devsdk/devsdk.h
- src/c/api.h
- src/c/bus.c
- src/c/discovery.c
- src/c/examples/discovery/template.c
- src/c/examples/template.c
- src/c/rest-server.c
- src/c/service.c
BREAKING CHANGE: Discovery function takes in request_id parameter now
Add request ID for discovery requests
Update to allow event publishing from a discovery function
> feat!: Publish System Events for device discovery and add discovery request ID

- docs/servicewritersguide.md
- include/devsdk/devsdk.h
- src/c/api.h
- src/c/devsdk-base.c
- src/c/discovery.c
- src/c/discovery.h
- src/c/examples/discovery/template.c
- src/c/service.c
- src/c/service.h
> feat: Implemented a discovery delete API

- include/devsdk/devsdk.h
- include/edgex/edgex.h
- src/c/autoevent.c
- src/c/config.c
- src/c/config.h
- src/c/device.c
- src/c/devman.c
- src/c/devmap.c
- src/c/examples/bitfields/device-bitfields.c
- src/c/metadata.c
- src/c/opstate.c
- src/c/opstate.h
- src/c/rest-server.c
- src/c/service.c
> feat: Add device up/down detection

- src/c/keeper.c
fix: #531 
Run device-random in secure mode and verify that it sends HTTP requests (e.g., reading/writing configuration, registering/deregistering, and querying services) to core-keeper without any errors.
> fix: Add JWT support for outgoing calls to core-keeper

- docs/configuration.md
- docs/startup.md
- src/c/examples/README.md
- src/c/examples/bitfields/README.md
- src/c/examples/counters/README.md
- src/c/examples/discovery/README.md
- src/c/examples/file/README.md
- src/c/examples/gyro/README.md
- src/c/examples/random/README.md
- src/c/examples/terminal/README.md
> fix: Update the commands in README files for running example device service

- src/c/device.c
- src/c/examples/discovery/template.c
- src/c/examples/template.c
> fix: Free iot_data_to_json results after use

- src/c/device.c
closes: #550
- Details are included in #550 
---
Thanks
> refactor(device-sdk-c): fix -Wformat-security warnings

- src/c/keeper.c
closes: #553
Follow #553 
---
Thanks.
> refactor(device-sdk-c): fix -Wformat argument warning

- src/c/device.c
fix: #555 
Adjust the transform logic to align with the Go SDK:
1. Perform max/min checks only if DataTransform is set to true.
2. Perform max/min checks before applying the transformation.
> fix: Follow the same transformation order as the Go Device SDK

- src/c/device.c
This is the missing piece from PR #562 
> fix: Update infoForRes func to allow device resource attributes to be undefined
