CHANGES, TODO, docs/deviceprofiles.md, docs/servicewritersguide.md, include/edgex/devsdk.h, include/edgex/edgex.h, src/c/data.c, src/c/data.h, src/c/device.c, src/c/edgex_rest.c, src/c/parson.c, src/c/service.c
Add support for Binary types and clean up some of the memory usage. In particular for types that are likely to have dynamically allocated memory (ie Binary and String) the memory is free'd in the SDK.
=> F 25 branch

include/edgex/edgex.h, src/c/callback.h, src/c/data.h, src/c/device.c, src/c/device.h, src/c/discovery.h, src/c/edgex_rest.c, src/c/edgex_rest.h, src/c/rest_server.h
Various parts of the EdgeX model defined in edgex/edgex.h are not needed by device service developers - move them into the "internal" header files.
Also two minor fixes for portability and brevity.
=> Header redundancy

CHANGES, TODO, include/edgex/edgex.h, src/c/device.c, src/c/edgex_rest.c
Addresses #88 
Inbound float data is autodetected as base64 or decimal regardless of settings
=> F-88 enable base64 encode/decode for floats

include/edgex/devsdk.h, include/edgex/edgex.h, include/edgex/os.h, src/c/callback.c, src/c/config.c, src/c/device.c, src/c/device.h, src/c/devman.c, src/c/devmap.c, src/c/devmap.h, src/c/edgex_rest.c, src/c/edgex_rest.h, src/c/profiles.c, src/c/rest_server.c, src/c/service.c, src/c/service.h
Bring the device and device profile datastructures together in their own class, for better maintainability.
Refcount devices so that we can handle a delete while an operation is in progress.
=> Encapsulate device map

CHANGES, include/edgex/device-mgmt.h, include/edgex/devsdk.h, include/edgex/edgex-base.h, include/edgex/edgex.h, include/edgex/registry.h, src/c/config.c, src/c/devman.c, src/c/discovery.c, src/c/edgex_rest.c, src/c/examples/template.c, src/c/profiles.c, src/c/service.c
+ Fix leftover reference to edgex_addressable relating to a device
+ Make discovery callback optional
=> Refactor: split out device management API into a seperate header

CHANGES, TODO, docs/configuration.md, include/edgex/registry.h, scripts/build.sh, src/c/config.c, src/c/config.h, src/c/consul.c, src/c/consul.h, src/c/errorlist.h, src/c/examples/res/configuration.toml, src/c/registry.c, src/c/rest.c, src/c/rest.h, src/c/service.c, src/c/service.h
Addresses #80 
Initial implementation allows for LogLevel to be reconfigured without restart. Other settings to be added later.
As this required further enhancements to the http client support, took the opportunity to rework rest.c and factor out much of the common code.
=> Dynamic configuration support

src/c/examples/template.c
If have two or more requests, the parameter of requests should be
directed to next object, otherwise all object will get the same value.
The example of profile config is below:
deviceCommands:
-
name: SensorOne
get:
- { index: "1", operation: "get", object: "SensorOne", parameter: "SensorOne", property: "value" }
- { index: "2", operation: "get", object: "SensorTwo", parameter: "SensorTwo", property: "value" }
In this case, the object "SensorOne" and "SensorTwo" will get the same value.
Signed-off-by: Sun Lianwen <sunlianwen@sgepri.sgcc.com.cn>
=> Add requests++ to compatible multiple requests

src/c/examples/res/ExampleProfile.yaml
The command  of put do not set parameterName, but the parameter is need
when exec put command.
Signed-off-by: Wei xingshen <weixingshen@sgepri.sgcc.com.cn>
=> Add parameterName in profile

CHANGES, include/edgex/devsdk.h, src/c/config.c, src/c/consul.c, src/c/data.c, src/c/devmap.c, src/c/devmap.h, src/c/examples/template.c, src/c/metadata.c, src/c/rest.c, src/c/service.c
Don't copy returned data from ping-type calls.
=> Split service_free function into stop() and free()

CHANGES, README.md, scripts/entrypoint.sh, src/CMakeLists.txt, src/c/CMakeLists.txt, src/c/autoevent.c, src/c/callback.c, src/c/callback.h, src/c/config.c, src/c/config.h, src/c/data.c, src/c/data.h, src/c/device.c, src/c/device.h, src/c/discovery.c, src/c/discovery.h, src/c/metrics.c, src/c/metrics.h, src/c/rest-server.c, src/c/rest-server.h, src/c/rest.c, src/c/rest.h, src/c/service.c, src/cmake/FindLibCBOR.cmake
#25 
NB this produces cbor-encoded events which look okay, and runs valgrind-clean, but current core-data does not yet support cbor so I've not been able to verify that it will accept what it is given.
=> CBOR encoding for Events containing Binary Readings

src/c/config.c, src/c/consul.c, src/c/data.c, src/c/edgex-rest.c, src/c/metrics.c, src/c/parson.c, src/c/parson.h
The new nanosecond timestamps for event/reading origin are sufficiently large that just using "double" for all numbers whether floating-point or not results in misrepresentations.
1) Include support for uint64 as an additional JSON object type
2) Parse numbers into uint64 if they fit, double (as before) otherwise
3) Allow uint64 to be retrieved and compared as if it was a double
4) Use this new type for all numbers that we use in EdgeX that are actually uints.
=> Fix precision loss when encoding large integers in JSON

CHANGES, docs/configuration.md, src/c/config.c, src/c/config.h, src/c/data.c, src/c/data.h, src/c/metadata.c, src/c/metadata.h, src/c/service.c
Make TOML parsing return name-value pairs like the registry does.
Rework the configuration part of service startup.
Use a generic ping function for supporting services.
Implements #147 
=> Allow config overrides from environment when populating the registry

CHANGES, include/edgex/devsdk.h, src/c/examples/counters/device-counter.c, src/c/examples/random/device-random.c, src/c/examples/template.c, src/c/service.c
As per #146 except that:
-  --help is left outside of the sdk (avoids having to bounce the help request back to the caller)
- the argument processing is an additional function rather than a change to service_new (so as not to change an existing API. Probably we'll consolidate this when we go to 2.0).
=> Process cmdline arguments in the sdk (#146)

docs/startup.md, src/c/service.c
Document environment variables and commandline options.
Implements #92 
=> Allow retry behavior for registry ping to be set via environment.

src/c/data.c
=> fix memleak on binary readings where the sdk sets the origin value

src/c/rest-server.c
the reserved namespace being anything prefixed 'ds-'
implements #180 
=> Don't pass query parameters in the reserved namespace

src/c/config.c
(when overriding config from environment) (#189)
=> Allow use of '_' in place of '-' in service name

README.md, scripts/Dockerfile.alpine-3.9, scripts/Dockerfile.alpine-3.9-base, scripts/entrypoint.sh, src/c/CMakeLists.txt
Move docker builds to Alpine 3.9
Use released version of CBOR library rather than HEAD ( Fixes #190 )
Declutter the output of the docker build
Add dockerfile for producing a container in which to build a service
=> Fixes for container build (supercedes #191)

include/edgex/edgex-base.h, include/edgex/edgex.h, src/c/callback.c, src/c/edgex-base.c, src/c/edgex-rest.c, src/c/edgex-rest.h, src/c/metadata.c, src/c/metadata.h, src/c/service.c, src/c/service.h, src/c/watchers.c, src/c/watchers.h
- Obtains PWs from core-metadata
- Updates PW list from core-metadata callbacks
- Includes outline of matching algorithm for use during discovery
=> Add initial provision watcher support (#8)

src/c/examples/counters/device-counter.c, src/c/examples/gyro/device-gyro.c, src/c/examples/random/device-random.c, src/c/examples/template.c, src/c/examples/terminal/device-terminal.c
=> Use NULL for default startup parameters. Avoids defaulting registry on.

CHANGES, docs/configuration.md, docs/startup.md, src/c/config.c, src/c/config.h, src/c/examples/v2/counters/device-counter.c, src/c/examples/v2/gyro/device-gyro.c, src/c/examples/v2/random/device-random.c, src/c/examples/v2/template.c, src/c/examples/v2/terminal/device-terminal.c, src/c/registry.c, src/c/service.c, src/c/service.h
* Add new environment variables (maintain old ones for v1 compat)
* Env vars now override cmdline
* Env vars can override config elements at any time
* Add new --configProvider and --file options
* Use consul.http to identify the consul registry implementation
=> Bring configuration behaviour into line with go-mod-bootstrap

docs/startup.md, src/c/service.c, src/c/v1compat.c
As per app-functions, device-sdk-go
=> compat: use --serviceName to override default service name

src/c/device.c, src/c/examples/counters/res/configuration.toml, src/c/examples/discovery/res/configuration.toml, src/c/examples/gyro/res/configuration.toml, src/c/examples/random/res/configuration.toml, src/c/examples/res/configuration.toml, src/c/examples/terminal/res/configuration.toml, src/c/examples/v2/gyro/res/configuration.toml, src/c/examples/v2/random/res/configuration.toml, src/c/examples/v2/terminal/res/configuration.toml, src/c/metadata.c, src/c/metadata.h
Example config files: use single quote for strings, increase retry count (as per other services)
Metadata client: URL-escape entity names that might need it
=> Small fixes

src/c/data.c, src/c/edgex-rest.c
Binary Readings are sent incomplete to core-data due to truncation of the map representing them
Binary Readings encoded correctly
=> fix: wrong map size for CBOR readings

src/c/metadata.c, src/c/service.c
Potential for driver's "stop" function to be called while service still active
Issue Number: #284 
Stop call moved to later in the shutdown process so that system is quiescent
=> refac: reorder shutdown sequence (#284) 

src/c/config.c, src/c/data.c, src/c/data.h, src/c/rest-server.c, src/c/service.c
By default, service listens on all interfaces
Issue Number: #278 
Default for Hanoi is to listen on a single interface
=> fix: align default behavior for listening interface with other services

src/c/api.h, src/c/config.c, src/c/device.c, src/c/edgex-rest.c, src/c/edgex-rest.h, src/c/edgex2.h, src/c/metrics.c, src/c/metrics.h, src/c/rest-server.c, src/c/service.c
v2 REST API PR 3/?
v2 spec for BaseResponse has been updated: need to re-sync the implementation
Issue Number: #257 
add v2 metrics endpoint
update v2 ping and config endpoints to current spec
This completes the common endpoints for v2. Device service endpoints (ie, discovery, callback, device) still not implemented / partially implemented
=> feat: REST v2 API common endpoints (#257)

include/edgex/edgex.h, src/c/devmap.c
The SDK holds device profiles in its cache indefinitely. This can lead to it being out of sync with core-metadata if profiles are updated.
A profile is purged from the cache when the last device using it is deleted. A fresh copy of the profile will be retrieved on-demand should a newly-created device require it.
=> fix: remove stale profiles when devices are removed

CHANGES, include/devsdk/devsdk.h, src/c/api.h, src/c/callback2.c, src/c/callback2.h, src/c/device.c, src/c/devmap.c, src/c/devmap.h, src/c/examples/bitfields/device-bitfields.c, src/c/examples/counters/device-counter.c, src/c/examples/discovery/template.c, src/c/examples/file/device-file.c, src/c/examples/gyro/device-gyro.c, src/c/examples/random/device-random.c, src/c/examples/template.c, src/c/examples/terminal/device-terminal.c, src/c/service.c, src/c/watchers.c
A number of minor updates have been made to the v2 REST API since its implementation in the CSDK. The SDK needs to be updated accordingly
* Allow query params on device put requests
* rename postevent queryparam to pushevent
* DeviceProfile add and delete callbacks are removed
* Device and Watcher delete callbacks are now by name not id
* Add Service update callback as per v1
* device/{id}/{command} not to be supported, only device/name/{name}/{command}
Additional parameter required on put-handler, to specify query parameters on the …
=> fix: update v2 REST API with recent changes

docs/deviceprofiles.md, include/devsdk/devsdk-base.h, include/edgex/edgex.h, src/c/device.c, src/c/devsdk-base.c, src/c/edgex-rest.c, src/c/examples/bitfields/res/profiles/Bitfields.yaml, src/c/examples/counters/res/profiles/Counter.yaml, src/c/examples/discovery/res/profiles/TemplateProfile.yaml, src/c/examples/file/res/profiles/FileExampleProfile.yaml, src/c/examples/gyro/res/profiles/Gyro.yaml, src/c/examples/random/res/profiles/RandomExampleProfile.yaml, src/c/examples/res/profiles/TemplateProfile.yaml, src/c/examples/terminal/README.md, src/c/examples/terminal/res/profiles/Terminal.yaml, src/c/transform.c
Update to new deviceCommand format, remove coreCommands from sample profiles
SDK expects device profiles in v1 format
Device profiles rationalized for EdgeX v2.0 
Device Profiles will need to be migrated to v2
=> fix: deviceProfile format changes (#310)

src/c/rest-server.c
Service fails to start if the resolved listener address is IPv6
Appropriate option set on server to support IPv6
=> fix: support ipv6 listener addresses (#332)

CHANGES, docs/configuration.md, include/edgex/edgex.h, src/c/autoevent.c, src/c/config.c, src/c/devman.c, src/c/devsdk-base.c, src/c/edgex-rest.c, src/c/examples/README.md, src/c/examples/bitfields/README.md, src/c/examples/bitfields/res/configuration.toml, src/c/examples/counters/README.md, src/c/examples/counters/res/configuration.toml, src/c/examples/counters/res/devices/Counters.json, src/c/examples/discovery/README.md, src/c/examples/discovery/res/configuration.toml, src/c/examples/file/res/configuration.toml, src/c/examples/gyro/README.md, src/c/examples/gyro/res/configuration.toml, src/c/examples/random/README.md, src/c/examples/random/res/configuration.toml, src/c/examples/random/res/devices/randomdevice1.json, src/c/examples/res/configuration.toml, src/c/examples/res/devices/device1.json, src/c/examples/terminal/README.md, src/c/examples/terminal/res/configuration.toml, src/c/metadata.c, src/c/metadata.h, src/c/service.c
No support for autoevent field in PWs
AutoEvent uses legacy `frequency` field
OperatingState update fails
Microservice names are prefixed with `edgex-`
Legacy port assignments in use by default
Discovery fails with segfault in the absence of labels for discovered devices
AutoEvents added to ProvisionWatchers
`interval` replaces `frequency`
Marshaling for operating state update request is corrected
Default ports moved to new assigned values
`null` checking added to discovery
AutoEvent specifications need to be updated with the renamed …
=> feat: support autoevent definitions in provision watchers (#309)

CHANGES, README.v2.md, docs/configuration.md, docs/servicewritersguide.md, include/devsdk/devsdk.h, src/c/autoevent.c, src/c/config.c, src/c/config.h, src/c/devsdk-base.c, src/c/devutil.h, src/c/examples/bitfields/device-bitfields.c, src/c/examples/bitfields/res/configuration.toml, src/c/examples/counters/device-counter.c, src/c/examples/counters/res/configuration.toml, src/c/examples/discovery/res/configuration.toml, src/c/examples/discovery/template.c, src/c/examples/file/device-file.c, src/c/examples/gyro/device-gyro.c, src/c/examples/gyro/res/configuration.toml, src/c/examples/random/device-random.c, src/c/examples/random/res/configuration.toml, src/c/examples/res/configuration.toml, src/c/examples/template.c, src/c/examples/terminal/device-terminal.c, src/c/examples/terminal/res/configuration.toml, src/c/service.c
Implementations must supply a callback function for dynamic reconfiguration even if they do not implement it
Reconfigure callback made optional.
Some configuration elements also moved / renamed to match Go service behavior
DS implementations need to have their callback population code updated
Configuration files need updating with new names / groups
Don't squash-merge
=> refactor: make reconfigure callback optional (#349)

docs/configuration.md, src/c/data-mqtt.c, src/c/data.h, src/c/device.c
Setting `MaxCmdOps` to zero disables reads
`MaxCmdOps` of zero results in no limits being applied
The (MessageBus)`Topic` configuration element is renamed to `PublishTopicPrefix` and its default value now includes the `device` element indicating messages which originate from a device service.
New topic config and default as above; aligns behavior with that of go-mod-messaging in v2
=> fix: MaxCmdOps of zero implies unlimited

src/c/edgex-rest.c, src/c/examples/template.c
When a device profile is parsed, if a device resource has no attributes, the SDK will segfault
SDK creates an empty attribute map if none have been specified
=> fix: avoid crash when deviceresource has no attributes

CHANGES, include/devsdk/devsdk.h, src/c/data-mqtt.c, src/c/data-mqtt.h, src/c/data-redstr.c, src/c/data-redstr.h, src/c/devsdk-base.c, src/c/devutil.h, src/c/registry.c, src/c/registry.h, src/c/service.c
Standard environment variables listed are ignored
SDK crashes on startup when MQTT is selected as the MessageQueue
#361 
Startup is controlled via the standard environment variables. MQTT initialization no longer refers to nonexistent configuration entries.
=> feat: support EDGEX_USE_REGISTRY, EDGEX_STARTUP_DURATION, EDGEX_STARTUP_INTERVAL

docs/startup.md, scripts/build.sh, src/c/config.c, src/c/data-mqtt.c, src/c/data-redstr.c, src/c/devsdk-base.c, src/c/devutil.h, src/c/edgex-logging.c, src/c/edgex-logging.h, src/c/examples/terminal/device-terminal.c, src/c/metadata.c, src/c/registry.c, src/c/service.c
Initial log level is set to TRACE resulting in much output during startup
Initial log level defaults to INFO. The service reads the override variable for log level early, so detailed startup logs may still be obtained.
This PR also brings the latest version of the utils dependency
=> fix: reduce startup logging by default (#370)

scripts/Dockerfile.alpine-base, src/c/autoevent.c, src/c/autoevent.h, src/c/devmap.c, src/c/edgex-rest.c
refac: eliminate recursion from dup/free list functions
Invalid reads may be observed in the main branch by running the template example under valgrind and removing Device1
=> fix: stop device autoevents before releasing memory

src/c/data-mqtt.c
MQTT library appears to include entire payload length including trailing
null. The events are being rejected by core-data with unmarshal errors.
Signed-off-by: Corey Mutter <CoreyMutter@eaton.com>
- [*] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [*] I am not introducing a new dependency (add notes below if you are)
- [*] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
=> Fix: Remove trailing null from MQTT message envelope (383)

src/c/registry.c, src/c/registry.h, src/c/service.c
Run the template example with --registry flag and with consul running but no core-data/core-metadata. Service startup should time out. Then try again but manually start core-data and core-metadata during the retry window (by default, a minute)
=> fix: retry attempts to resolve service endpoints from registry (#394)

src/c/device.c
Found that ds-pushevent and ds-returnevent were being ignored. Turns out
those live in req->qparams rather than req->params.
Closes: edgexfoundry#409
Signed-off-by: Corey Mutter <CoreyMutter@eaton.com>
I tested in a local custom device service; it can probably be tested against one of the SDK's example services.
=> fix: don't ignore ds-pushevent and ds-returnevent

CHANGES, docs/servicewritersguide.md, include/devsdk/devsdk.h, src/c/api.h, src/c/devsdk-base.c, src/c/edgex-rest.c, src/c/edgex-rest.h, src/c/metadata.c, src/c/metrics.c, src/c/service.c, src/c/service.h, src/c/validate.c, src/c/validate.h
refac: use new mallinfo() replacement if available
fix: parse multi-status return from device create
Add a function `template_validate_pps (void *impl, const devsdk_protocols *protocols, iot_data_t **exception)` to the template example and register it using `devsdk_callbacks_set_validate_addr (templateImpls, template_validate_pps);`
Verify that when a device is added (eg at startup) the function is called, and if it sets an exception the device addition fails
=> feat: add ProtocolProperties validation (#402)

src/c/consul.c, src/c/secrets-impl.h, src/c/secrets-insecure.c, src/c/secrets-vault.c, src/c/secrets.c, src/c/secrets.h, src/c/service.c
- Add a call to `devsdk_get_secrets()` in the template example
- Create a time-limited vault token using eg `vault token create -period=2m`
- Run the example in secure mode
- The get_secrets operation should continue to succeed after the 2 minute renewal period
=> feat: renew Vault tokens before they expire (fix #423)

CHANGES, src/c/config.c, src/c/data-mqtt.c, src/c/data-mqtt.h, src/c/data-redstr.c, src/c/data.h
Closes #374
Enable MessageBus in the example (Device/UseMessageBus = true, MessageQueue/Type = "redis") and send requests via core-command
=> feat: Add Redis subscriber for commands

CHANGES, src/c/autoevent.c, src/c/config.c, src/c/config.h, src/c/data-mqtt.c, src/c/data-redstr.c, src/c/data-rest.c, src/c/data.c, src/c/data.h, src/c/device.c, src/c/metrics.h, src/c/secrets.c, src/c/secrets.h, src/c/service.c, src/c/service.h
closes #415
Configure the template example for Redis MessageQueue, and enable some metrics, eg
```
[Writable.Telemetry.Metrics]
EventsSent = true
ReadingsSent = true
```
Observe publications using `redis-cli monitor`
=> feat: add metrics publication

src/c/bus-mqtt.c
The allocated block in the pointers *topicName and *message passed by MQTT library cannot be re-allocated.
fix: #468 
Download and update the [configuration file](https://docs.edgexfoundry.org/3.1/getting-started/Ch-GettingStartedSDK-C/#configuring-your-device-service) of device-example-c to use mqtt-bus
```
MessageBus:
Protocol: tcp
Host: localhost
Port: 1883
Type: mqtt
AuthMode: "none" 
```
Run non-secure EdgeX stack with mqtt-bus
Build and run [device-example-c](https://docs.edgexfoundry.org/3.1/getting-started/Ch-Get …
=> fix: invalid pointer operation in edgex_bus_mqtt_msgarrvd

src/c/bus.c
fix: #466 
Run device-example-c https://docs.edgexfoundry.org/3.0/getting-started/Ch-GettingStartedSDK-C/#run-your-device-service and verify if events are being created successfully.
=> fix: update edgex_data_to_b64 to ignore the last null character

src/c/examples/file/README.md, src/c/service.c
fix #464
Run EdgeX stack
Build and run the file monitor example (src/c/examples/file/device-example-c)
=> fix: update devsdk_post_readings to alloc and free correction id

src/c/dto-read.c, src/c/examples/bitfields/README.md, src/c/examples/bitfields/res/configuration.yaml, src/c/examples/bitfields/res/profiles/Example-Bitfields.json
fix: #475 
https://github.com/edgexfoundry/edgex-docs/pull/1180
Run EdgeX stack
Follow the instructions in /src/c/examples/bitfields/README.md to run the device-bitfields example
=> fix: update edgex_get_transformArg to reflect data type changes in ResourceProperties

src/c/bus-redstr.c, src/c/bus.h, src/c/config.c, src/c/config.h, src/c/consul.c, src/c/examples/bitfields/res/configuration.yaml, src/c/examples/counters/res/configuration.yaml, src/c/examples/discovery/res/configuration.yaml, src/c/examples/file/res/configuration.yaml, src/c/examples/gyro/res/configuration.yaml, src/c/examples/random/res/configuration.yaml, src/c/examples/res/configuration.yaml, src/c/examples/terminal/res/configuration.yaml, src/c/registry-impl.h, src/c/registry.c, src/c/registry.h, src/c/service.c, src/c/service.h
fix: #481 
Non-secure mode testing
1. From the latest compose builder run `make run no-secty`.
2. Run device-random example (/src/c/examples/random) with `-cp=consul.http://localhost:8500 --registry` arguments.
3. Verify that the device-random configuration has been written to Consul K/V Store.
4. Update Writable configuration for device-random and core-common-config-bootstrapper on Consul K/V Store, and then verify if it takes effect.
Secure mode testing
1. From the latest compose builder, modify add-security.yml to …
=> feat!: load common configuration from config provider

src/c/api.h, src/c/consul.c, src/c/examples/commonconfiguration.yaml, src/c/service.c, src/c/service.h
fix: #485 
Hold until https://github.com/edgexfoundry/device-sdk-c/pull/484 is merged
**Non-secure mode testing**
1. From the latest compose builder run `make run no-secty`.
2. Set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=false`
3. Run device-random example (/src/c/examples/random) with `-cc=../commonconfiguration.yaml` argument.
4. The device-random service should bootstrap successfully without having the following error
```
level=ERROR ts=2023-10-06T04:34:11Z app=device-random msg="Unable to load common config file: Unable to open configuration file"
Error: 1: Unable to open configuration file
```
5. The configuration can also be verified through the REST API: …
=> feat: Add command line/environment flag for commonConfig 

src/c/reqdata.c
fix:If the put request's json payload is string type, The slash of a string cannot be removed using json_serialize_to_string.
example: {"command": "open"} → {\"command\": \"open\"} → \open\
=> fix:If the put request's json payload is string type, The slash of a string cannot be removed using json_serialize_to_string.

src/c/data.c
When reading's value is string type, it will be released prematurely.
---------------
ae_runner → edgex_data_process_event → devsdk_commandresult_free
string of IOT_DATA_REF will be release prematurely by devsdk_commandresult_free
---------------
=> fix:When reading's value is string type, it will be released prematurely

src/c/service.c
fix: #503 
Run the [file monitor example](https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/file) with Valgrind memcheck
=> fix: memory leaks in devsdk_post_readings function

src/c/dto-read.c, src/c/dto-read.h
fix: #482 
1. Run the [random generator example](https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/random) in debug mode and set a breakpoint at https://github.com/edgexfoundry/device-sdk-c/blob/6bdae90b977cdeecb957260a94da902cfcf10c29/src/c/callback3.c#L80
2. Update device
```
curl -X 'PATCH' \
'http://localhost:59881/api/v3/device' \
-d '[
{
"apiVersion": "v2",
"device": {
"name": "RandomDevice1",
"labels": [
"label1", "label2"
]
}
}
]'
```
3. Check the device read by `edgex_device_read`  in step 1
=> fix: edgex_device_read does not read labels

src/c/config.c, src/c/consul.c, src/c/dto-read.c, src/c/edgex-rest.c, src/c/examples/discovery/template.c, src/c/examples/template.c, src/c/secrets-insecure.c, src/c/transform.c, src/c/validate.c, src/c/watchers.c
Sometimes objects intended to be maps are null, or initialized but type IOT_DATA_NULL, causing map get/iterate functions to assert. Bypass these cases, treating it as an empty map.
- [ x ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ x ] I am not introducing a new dependency (add notes below if you are)
=> fix: assert failures on null/empty maps (Closes #504)

src/c/metadata.c
Fetch the entire list of devices from core-metadata at startup.
Fixes: #555
This one comes from my team and has been in place locally for a year now, with no ill effects even on systems with 10K+ devices on one service.
=> fix: Only 20 devices end up in devmap (#555)

src/c/service.c, src/c/service.h
Fixes the missing discover delete setup for secure mode
=> fix: Missing discovery delete wrapper for secure mode

src/c/bus-mqtt.c
fix: #522 
Tested with the latest [edgex-compose](https://github.com/edgexfoundry/edgex-compose), where the message bus protocol is set to `mqtt`.
=> fix: Add support for additional MQTT protocol aliases

src/c/bus.c
The single-level wildcard `+` is not supported because it increases complexity, and there is currently no requirement for it.
fix: #523 
=> feat: Handle wildcard `#` in base path for message bus handler matching

src/c/keeper.c, src/c/keeper.h, src/c/registry.c, src/c/registry.h, src/c/service.c
=> feat: Support core-keeper for registry and config.

src/c/bus-mqtt.c
MQTTAsync_subscribe() is async. There are some places e.g. startConfigured() where we expect the subscription to be in effect right after this call. So wait for completion before returning.
Fixes: #516 
Before and after change, on a busy system, repeatedly have a C-based device service start and upload its devices (deleting them from core-metadata each time), to reproduce the bug in the related issue.
=> fix: Wait for MQTT subscriptions to take effect before returning (#516)

src/c/service.c
=> fix: Allow `-cp` flag to work without `-r` flag

src/c/keeper.c
fix: #529 
1. Run device-random https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/random
2. Update common config (all-services) via the core-keeper REST API
```
curl -X 'PUT'   'http://localhost:59890/api/v3/kvs/key/edgex/v4/core-common-config-bootstrapper/all-services/Writable/Telemetry/Interval?flatten=false'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
"value": "5s"
}'
```
3. Update common config (device-services) via the core-keeper REST API
```
curl -X 'PUT' …
```
=> feat: Add support for listening to common config changes from core-keeper

src/c/bus-impl.h, src/c/bus.c
BREAKING CHANGE: Use JSON object in message envelope payload instead of base64 string
Add a new flag `msgb64payload` to the `edgex_bus_t` structure to support optional Base64 payload. This flag is configurable via the environment variable `EDGEX_MSG_BASE64_PAYLOAD` and defaults to `false`.
fix: #538 
Run device-random and make sure Events, System Events, and Metrics all work fine.
=> feat!: Use JSON object in message envelope payload instead of base64 string

src/c/data.c, src/c/data.h, src/c/device.c
fix: #547 #546 
1. Run the [device-random example](https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/random) with [Valgrind](https://valgrind.org/) to check for memory leaks:
```
valgrind --leak-check=full ./device-random -cp=keeper.http://localhost:59890 -r
```
2. Issue core commands:
```
curl 'http://localhost:59882/api/v3/device/name/RandomDevice1/SensorOne?ds-pushevent=false&ds-returnevent=false'
curl 'http://localhost:59882/api/v3/device/name/RandomDevice1/SensorOne?ds-pushevent=true&ds-returneve …
```
=> fix: properly free edgex_event_cooked

src/c/device.c
fix: #561 
Test using the [device-bitfields example](https://github.com/edgexfoundry/device-sdk-c/tree/main/src/c/examples/bitfields) in the sdk to confirm that core commands execute correctly.
=> fix: Make device resource attributes optional

src/c/service.c
closes: #566
Instructions are included in #566 
Test instructions are minimal since warning only appears in build process.
---
Thanks
=> refactor(device-sdk-c): fix Wmaybe-uninitialized warning

src/c/bus-mqtt.c
This fixes a bug in `edgex_bus_create_mqtt()` where the `result` pointer is freed but not nullified,
resulting in a dangling pointer and potential undefined behavior.
- Explicitly set `result = NULL` after `free(result)` in the error path.
- Verified that on error path, `result` returned is `NULL`.
- Ran SDK unit tests (if any) and ensured `make checkstyle` passes.
Signed-off-by: sudarsan N <sudarsansamy2002@gmail.com>
=> fix(mqtt): nullify result pointer after free in edgex_bus_create_mqtt()

src/c/bus-mqtt.c
Ensure that MQTTAsync_destroy() is called in the failure path of edgex_bus_create_mqtt when the connection fails. This prevents resource leaks caused by the uncleaned MQTT client instance.
Previously, only free() was called on cinfo without destroying the client.
=> fix(mqtt): destroy MQTTAsync client on failed connection setup

include/devsdk/devsdk.h, src/c/callback3.c, src/c/devsdk-base.c, src/c/service.h
There are certain use cases where profile entries are important at the service side and hence any modification is required to be notified to the service. For current initial phase, listener callback would only have info about the profile name so that developers can atleast use the function "edgex_get_deviceprofile_byname" on profile update listener callback trigger at the service side to get the updated profile details and take action accordingly from the service point of view.
Checking entire parameters w.r.t. device-resources/commands under the updated device profile seems to be a tricky part to get the profile update listener callback triggerred. Hence, going now with a simpler approach of only passing updated profile name as info for the callback so that the service gets to know that …
=> feat!: Add profile management support in order to get notification at the service side in case there is some update on associated device profile
